# Generated by Django 6.0.2 on 2026-04-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='teacher_id',
            field=models.IntegerField(null=True, unique=True),
            preserve_default=False,
        ),
    ]
