# Generated by Django 6.0.2 on 2026-04-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0002_teachers_teacher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='teachers',
            name='teacher_id',
            field=models.IntegerField(unique=True),
        ),
    ]
